Closes #2 - EF Core implementation
teddyBear000/Lanthanum-dev pull request #29
Opened 2021-08-19 22:00 UTC by oleksandrmanetskyi

2021-08-19 22:08 UTC, Rev1kon approved these changes

2021-08-19 22:17 UTC, ignars3 commented on Lanthanum.Data/Repositories/DbRepository.cs
> +            await Context.SaveChangesAsync();
Думаю буде правильніше створити функцію SaveAsync і використовувати безпосередньо її в інших функціях

2021-08-20 03:04 UTC, IhorMruchko approved these changes

2021-08-20 08:19 UTC, BorysKopytko commented on Lanthanum.Data/Domain/User.cs
> +        InActivated,
![image](https://user-images.githubusercontent.com/87943416/130203162-3b092762-5a2a-4bb5-919b-70481081a382.png)

2021-08-20 08:23 UTC, BorysKopytko requested changes
Please check comments.

2021-08-20 10:59 UTC, BorysKopytko approved these changes
Everything is OK.

2021-08-21 11:48 UTC, bohdanburda approved these changes

2021-08-21 11:57 UTC, TitanMaiden approved these changes

2021-08-21 12:06 UTC, merged