032 interaction with existing comments
teddyBear000/Lanthanum-dev pull request #43
Opened 2021-09-22 00:25 UTC by Rev1kon

Requesting review.

2021-09-22 13:58 UTC, BorysKopytko requested changes

2021-09-22 13:58 UTC, BorysKopytko commented on Lanthanum.Web/wwwroot/css/comments.css
> +    .blog-comment .headings {
Use Ctrl+K and Ctrl+D to format file.

2021-09-22 13:59 UTC, Rev1kon commented on Lanthanum.Web/wwwroot/css/comments.css
> +    .blog-comment .headings {
Ти про те що там є табуляція?

2021-09-22 14:03 UTC, BorysKopytko commented on Lanthanum.Web/wwwroot/css/comments.css
> +    .blog-comment .headings {
Так.

2021-09-22 14:05 UTC, Rev1kon commented on Lanthanum.Web/wwwroot/css/comments.css
> +    .blog-comment .headings {
Це наслідування стилів, воно виставляє табуляцію автоматично.

2021-09-22 14:07 UTC, BorysKopytko commented on Lanthanum.Web/wwwroot/css/comments.css
> +    .blog-comment .headings {
Гаразд, тримай мій апрув :)

2021-09-22 14:08 UTC, BorysKopytko approved these changes
Everything is OK.

2021-09-22 14:08 UTC, Rev1kon commented on Lanthanum.Web/wwwroot/css/comments.css
> +    .blog-comment .headings {
<3

2021-09-22 22:05 UTC, TitanMaiden approved these changes

2021-09-23 18:17 UTC, ignars3 approved these changes

2021-09-24 07:49 UTC, bohdanburda approved these changes

2021-09-24 12:59 UTC, oleksandrmanetskyi approved these changes

2021-09-24 20:24 UTC, merged